"""added status

Revision ID: 8386d7d7ece1
Revises: 
Create Date: 2025-02-09 15:32:55.580770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8386d7d7ece1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.CHAR(length=15),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'working'::bpchar"))
        batch_op.drop_column('privilege')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privilege', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.CHAR(length=15),
               nullable=True,
               existing_server_default=sa.text("'working'::bpchar"))

    # ### end Alembic commands ###
