"""added last comment time

Revision ID: b53f102b02d1
Revises: 009ae7abbae5
Create Date: 2025-02-09 20:05:06.462971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53f102b02d1'
down_revision = '009ae7abbae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_comment_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('last_comment_time')

    # ### end Alembic commands ###
